import React, { useState } from 'react';
import type { PredictionModule } from '../../types/analysis';
import { Cpu, Search, Info, BarChart2, TrendingUp, TrendingDown } from 'lucide-react';

interface CustomerRiskTableProps {
  predictions?: PredictionModule;
}

export const CustomerRiskTable: React.FC<CustomerRiskTableProps> = ({ predictions }) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [tierFilter, setTierFilter] = useState<'All' | 'High' | 'Medium' | 'Low'>('All');

  if (!predictions) return null;

  const filteredCustomers = predictions.customers.filter((c) => {
    const matchesSearch =
      c.customer_id.toLowerCase().includes(searchTerm.toLowerCase()) ||
      JSON.stringify(c.key_attributes).toLowerCase().includes(searchTerm.toLowerCase());
    const matchesTier = tierFilter === 'All' || c.risk_tier === tierFilter;
    return matchesSearch && matchesTier;
  });

  return (
    <section id="predictions" className="w-full mb-16" aria-label="Per-Customer Churn Risk Scores">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-end justify-between mb-6 pb-4 border-b border-[#2e2e2e]">
        <div>
          <div className="flex items-center gap-2 text-[#847dff] font-mono-data text-[12px] uppercase tracking-wider mb-1">
            <Cpu className="w-4 h-4" aria-hidden="true" />
            <span>Predictive Machine Learning Module</span>
          </div>
          <h2 className="font-serif-display text-[32px] sm:text-[38px] font-light text-[#ffffff] leading-tight">
            Per-Customer Churn Risk Scoring
          </h2>
        </div>
        <div className="flex items-center gap-3 mt-3 sm:mt-0">
          <div className="px-3 py-1.5 rounded-[8px] bg-[#2e2e2e] border border-[#3f4041] text-[12px] font-mono-data text-[#00b3dd]">
            ROC-AUC: <span className="font-bold text-[#ffffff]">{predictions.model_metrics.auc.toFixed(3)}</span>
          </div>
          <div className="px-3 py-1.5 rounded-[8px] bg-[#2e2e2e] border border-[#3f4041] text-[12px] font-mono-data text-[#847dff]">
            Precision: <span className="font-bold text-[#ffffff]">{(predictions.model_metrics.precision * 100).toFixed(0)}%</span>
          </div>
        </div>
      </div>

      {/* Disclaimer Banner */}
      <div className="mb-6 p-4 rounded-[12px] bg-[#847dff]/[0.08] border border-[#847dff]/30 text-[#d1c9ff] flex items-start gap-3" role="note">
        <Info className="w-5 h-5 text-[#847dff] shrink-0 mt-0.5" aria-hidden="true" />
        <div className="text-[13px] font-sans-ui leading-relaxed">
          <strong className="text-[#ffffff]">Important Distinction:</strong> Sections 2–4 present overall{' '}
          <em>historical statistical correlations</em> across your dataset. This section presents{' '}
          <em>individual machine learning probability predictions</em> generated by a trained Random Forest model.
          Confidence intervals (±) show prediction uncertainty from individual tree variance.
        </div>
      </div>

      {/* Feature Importance Summary Bar */}
      <div className="mb-8 p-6 bg-[#090a0b] border border-[#2e2e2e] rounded-[16px]">
        <h3 className="font-mono-data text-[12px] uppercase text-[#9f9fa0] tracking-wider mb-4 flex items-center gap-2">
          <BarChart2 className="w-4 h-4 text-[#847dff]" aria-hidden="true" />
          <span>Global Feature Importance Drivers (Model Weights)</span>
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {predictions.feature_importance.map((fi) => (
            <div key={fi.feature} className="bg-[#0f1011] p-3 rounded-[8px] border border-[#2e2e2e]">
              <div className="flex justify-between text-[12px] mb-1.5">
                <span className="text-[#ffffff] font-medium truncate">{fi.feature}</span>
                <span className="font-mono-data text-[#847dff]">{(fi.importance * 100).toFixed(0)}%</span>
              </div>
              <div className="w-full h-1.5 bg-[#2e2e2e] rounded-full overflow-hidden" role="progressbar" aria-valuenow={fi.importance * 100} aria-valuemin={0} aria-valuemax={100}>
                <div className="h-full bg-[#847dff] rounded-full" style={{ width: `${fi.importance * 100}%` }} />
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4 mb-4">
        <div className="relative w-full sm:w-[320px]">
          <Search className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-[#6a6b6b]" aria-hidden="true" />
          <input
            type="text"
            placeholder="Search Customer ID or attributes..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            aria-label="Search customers by ID or attributes"
            className="w-full bg-[#090a0b] border border-[#3f4041] rounded-[8px] pl-10 pr-4 py-2 text-[13px] text-[#ffffff] focus:outline-none focus:border-[#847dff]"
          />
        </div>

        <div className="flex items-center gap-2 w-full sm:w-auto" role="group" aria-label="Filter by risk tier">
          <span className="text-[12px] text-[#6a6b6b] font-mono-data">Filter Risk Tier:</span>
          {(['All', 'High', 'Medium', 'Low'] as const).map((tier) => (
            <button
              key={tier}
              onClick={() => setTierFilter(tier)}
              aria-pressed={tierFilter === tier}
              className={`px-3 py-1 rounded-[6px] text-[12px] font-mono-data transition-colors cursor-pointer ${
                tierFilter === tier
                  ? 'bg-[#847dff] text-[#000000] font-bold'
                  : 'bg-[#2e2e2e] text-[#9f9fa0] hover:text-[#ffffff]'
              }`}
            >
              {tier}
            </button>
          ))}
        </div>
      </div>

      {/* Customer Risk Table */}
      <div className="bg-[#090a0b] border border-[#2e2e2e] rounded-[16px] overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse" role="table" aria-label="Customer churn risk scores">
            <thead>
              <tr className="bg-[#0f1011] border-b border-[#2e2e2e] text-[#6a6b6b] font-mono-data text-[12px] uppercase">
                <th className="py-3.5 px-6" role="columnheader">Customer ID</th>
                <th className="py-3.5 px-6" role="columnheader">Churn Probability</th>
                <th className="py-3.5 px-6" role="columnheader">Risk Tier</th>
                <th className="py-3.5 px-6 hidden lg:table-cell" role="columnheader">Top Drivers</th>
                <th className="py-3.5 px-6" role="columnheader">Key Attributes</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#2e2e2e]">
              {filteredCustomers.map((c) => {
                const probPct = (c.churn_probability * 100).toFixed(0);
                const badgeColor =
                  c.risk_tier === 'High'
                    ? 'bg-[#ff4d4d]/15 text-[#ff4d4d] border-[#ff4d4d]/30'
                    : c.risk_tier === 'Medium'
                    ? 'bg-[#ffaa00]/15 text-[#ffaa00] border-[#ffaa00]/30'
                    : 'bg-[#00b3dd]/15 text-[#00b3dd] border-[#00b3dd]/30';

                const barColor =
                  c.risk_tier === 'High' ? 'bg-[#ff4d4d]'
                  : c.risk_tier === 'Medium' ? 'bg-[#ffaa00]'
                  : 'bg-[#00b3dd]';

                // Confidence interval display
                const hasCI = c.churn_prob_low != null && c.churn_prob_high != null;
                const ciStr = hasCI
                  ? `${(c.churn_prob_low! * 100).toFixed(0)}–${(c.churn_prob_high! * 100).toFixed(0)}%`
                  : null;

                return (
                  <tr key={c.customer_id} className="hover:bg-[#2e2e2e]/50 transition-colors">
                    <td className="py-4 px-6 font-mono-data text-[14px] text-[#ffffff] font-semibold">
                      {c.customer_id}
                    </td>
                    <td className="py-4 px-6">
                      <div className="flex items-center gap-3">
                        <div>
                          <span className="font-mono-data font-bold text-[14px] text-[#ffffff] block">
                            {probPct}%
                          </span>
                          {ciStr && (
                            <span className="text-[10px] font-mono-data text-[#6a6b6b]" aria-label={`Confidence interval ${ciStr}`}>
                              CI: {ciStr}
                            </span>
                          )}
                        </div>
                        <div className="w-20 h-2 bg-[#1a1a1a] rounded-full overflow-hidden" role="progressbar" aria-valuenow={Number(probPct)} aria-valuemin={0} aria-valuemax={100}>
                          <div className={`h-full rounded-full ${barColor}`} style={{ width: `${probPct}%` }} />
                        </div>
                      </div>
                    </td>
                    <td className="py-4 px-6">
                      <span className={`inline-flex items-center px-3 py-1 rounded-full text-[12px] font-mono-data font-semibold border ${badgeColor}`}>
                        {c.risk_tier} Risk
                      </span>
                    </td>
                    {/* Per-customer top drivers — hidden on small screens */}
                    <td className="py-4 px-6 hidden lg:table-cell">
                      {c.top_drivers && c.top_drivers.length > 0 ? (
                        <div className="flex flex-col gap-1">
                          {c.top_drivers.slice(0, 3).map((d, i) => (
                            <div key={i} className="flex items-center gap-1.5 text-[11px] font-sans-ui">
                              {d.direction === 'increases' ? (
                                <TrendingUp className="w-3 h-3 text-[#ff4d4d] shrink-0" aria-hidden="true" />
                              ) : (
                                <TrendingDown className="w-3 h-3 text-[#00b3dd] shrink-0" aria-hidden="true" />
                              )}
                              <span className="text-[#9f9fa0] truncate max-w-[140px]">{d.feature}</span>
                            </div>
                          ))}
                        </div>
                      ) : (
                        <span className="text-[11px] text-[#6a6b6b]">—</span>
                      )}
                    </td>
                    <td className="py-4 px-6">
                      <div className="flex flex-wrap gap-2 text-[12px] text-[#9f9fa0] font-sans-ui">
                        {Object.entries(c.key_attributes).map(([key, val]) => (
                          <span key={key} className="bg-[#0f1011] px-2.5 py-1 rounded-[6px] border border-[#2e2e2e]">
                            <span className="text-[#6a6b6b]">{key}:</span> {val}
                          </span>
                        ))}
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
};
